# Generated by Django 5.2.7 on 2026-02-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phonte_number',
            new_name='phone_number',
        ),
    ]
